version: '3'

services:
  nginx:
     container_name: koperasi
     image: nginx:1.17
     build:
       context: .
     volumes:
       - .:/app
       - ./app/node_modules
     ports:
       - "3020:80"
     networks:
       - koperasi